// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/metricSaverService.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetricSaverService_UpdateMetrics_FullMethodName = "/services.MetricSaverService/UpdateMetrics"
)

// MetricSaverServiceClient is the client API for MetricSaverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricSaverServiceClient interface {
	UpdateMetrics(ctx context.Context, in *SaveMetricsRequest, opts ...grpc.CallOption) (*SaveMetricsResponse, error)
}

type metricSaverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricSaverServiceClient(cc grpc.ClientConnInterface) MetricSaverServiceClient {
	return &metricSaverServiceClient{cc}
}

func (c *metricSaverServiceClient) UpdateMetrics(ctx context.Context, in *SaveMetricsRequest, opts ...grpc.CallOption) (*SaveMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveMetricsResponse)
	err := c.cc.Invoke(ctx, MetricSaverService_UpdateMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricSaverServiceServer is the server API for MetricSaverService service.
// All implementations should embed UnimplementedMetricSaverServiceServer
// for forward compatibility.
type MetricSaverServiceServer interface {
	UpdateMetrics(context.Context, *SaveMetricsRequest) (*SaveMetricsResponse, error)
}

// UnimplementedMetricSaverServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricSaverServiceServer struct{}

func (UnimplementedMetricSaverServiceServer) UpdateMetrics(context.Context, *SaveMetricsRequest) (*SaveMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMetrics not implemented")
}
func (UnimplementedMetricSaverServiceServer) testEmbeddedByValue() {}

// UnsafeMetricSaverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricSaverServiceServer will
// result in compilation errors.
type UnsafeMetricSaverServiceServer interface {
	mustEmbedUnimplementedMetricSaverServiceServer()
}

func RegisterMetricSaverServiceServer(s grpc.ServiceRegistrar, srv MetricSaverServiceServer) {
	// If the following call pancis, it indicates UnimplementedMetricSaverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricSaverService_ServiceDesc, srv)
}

func _MetricSaverService_UpdateMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricSaverServiceServer).UpdateMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricSaverService_UpdateMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricSaverServiceServer).UpdateMetrics(ctx, req.(*SaveMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetricSaverService_ServiceDesc is the grpc.ServiceDesc for MetricSaverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricSaverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.MetricSaverService",
	HandlerType: (*MetricSaverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateMetrics",
			Handler:    _MetricSaverService_UpdateMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/metricSaverService.proto",
}
